FROM node:18

# Install Java
RUN apt-get update && apt-get install -y openjdk-17-jre

WORKDIR /app

COPY ./backend/functions/package.json ./functions/

WORKDIR /app/functions

RUN npm install

WORKDIR /app

COPY ./backend .

RUN npm install -g firebase-tools

EXPOSE 4000 5000   

CMD ["firebase", "emulators:start"]